CREATE TABLE MEMBER (
    ID VARCHAR2(50) PRIMARY KEY,       -- 아이디
    PW VARCHAR2(50) NOT NULL,          -- 비밀번호
    NICKNAME VARCHAR2(50) NOT NULL,    -- 닉네임
    PIC VARCHAR2(500),                 -- ★사진 파일명 (글자)
    JOIN_DATE DATE DEFAULT aSYSDATE     -- 가입일 (오라클 시간)
);

CREATE TABLE BOARD (
    B_NO NUMBER PRIMARY KEY,           -- 글번호 (숫자)
    B_TAG VARCHAR2(20) NOT NULL,       -- 태그 (강아지/고양이)
    B_TITLE VARCHAR2(200) NOT NULL,    -- 제목
    B_CONTENT CLOB NOT NULL,           -- 내용 (긴 글은 CLOB)
    B_PIC VARCHAR2(500),               -- 게시글 사진
    B_WRITER VARCHAR2(50) NOT NULL,    -- 작성자 ID    
    B_NICKNAME VARCHAR2(50) NOT NULL,  -- 작성자 닉네임
    B_DATE DATE DEFAULT SYSDATE,       -- 작성일
    B_VIEWS NUMBER DEFAULT 0,          -- 조회수
    B_LIKES NUMBER DEFAULT 0           -- 좋아요
);

-- 게시판 글번호 자동 생성기 (시퀀스)
CREATE SEQUENCE BOARD_SEQ;

CREATE TABLE REPLY (
    R_NO NUMBER PRIMARY KEY,           -- 댓글 번호
    B_NO NUMBER NOT NULL,              -- 어느 글의 댓글인지
    R_WRITER VARCHAR2(50) NOT NULL,    -- 댓글 작성자
    R_CONTENT VARCHAR2(1000) NOT NULL, -- 댓글 내용
    R_DATE DATE DEFAULT SYSDATE,       -- 작성일
    
    -- 게시글이 지워지면 댓글도 같이 지워지는 옵션
    CONSTRAINT FK_REPLY_BOARD FOREIGN KEY (B_NO)
    REFERENCES BOARD(B_NO) ON DELETE CASCADE
);

CREATE TABLE BOARD_LIKE (
    ID VARCHAR2(50),
    B_NO NUMBER,
    LIKE_DATE DATE DEFAULT SYSDATE,
    PRIMARY KEY (ID, B_NO)
);


CREATE SEQUENCE REPLY_SEQ;

COMMIT;

SELECT * from member;

CREATE TABLE PET (
    PET_NO    NUMBER         PRIMARY KEY,
    MEMBER_ID VARCHAR2(100)  NOT NULL,
    PET_NAME  VARCHAR2(50)   NOT NULL,
    PET_PIC   CLOB,
    REG_DATE  DATE           DEFAULT SYSDATE,
    
    CONSTRAINT FK_PET_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER(ID) ON DELETE CASCADE
);

CREATE SEQUENCE PET_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

CREATE INDEX IDX_PET_MEMBER ON PET(MEMBER_ID);

COMMIT;
ALTER TABLE BOARD MODIFY B_TAG      NVARCHAR2(20);
ALTER TABLE BOARD MODIFY B_TITLE    NVARCHAR2(200);
ALTER TABLE BOARD MODIFY B_CONTENT  NCLOB;
ALTER TABLE BOARD MODIFY B_NICKNAME NVARCHAR2(50);
COMMIT;